---
title: "How Teacher Characteristics Correlate with Student Test Scores: Evidence from Texas ESC Region 20"
author: "Evy Lanay and Alberto Saldarriaga"
date: today
date-format: long
format: 
    beamer:
        eval: false
        echo: true
        aspectratio: 169
        theme: default
        toc: false
        header-includes:
            \setbeamertemplate{footline}[frame number]
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
---

```{python}
#| echo: false
#| eval: true
import pandas as pd
import altair as alt
```


# Background & Motivation
## Teachers & Student Success
- A teacher's quality can greatly influence students' academic outcomes.
- Characteristics such as having an advanced degree or more years of teaching experience may contribute to higher-quality teaching.
- Additionally, schools may perform better overall if they can maintain high rates of teacher retention, as teacher turnover can negatively impact students.

## Texas Education Service Center 20
- We draw from public, school district-level data in one of Texas' 20 education regions (ESC Region 20), which has 58 districts.
- The most urban part of this region is San Antonio, Texas (population: 1.5 million), but there are extremely rural parts as well, in addition to counties that border Mexico.
- This region provides diverse insights into the relatonship between teacher characteristics and student outcomes in a wide range of contexts.

## Data: Variables and Metrics
- 
- 
- 

## Slide 4 Title



## Slide 5 Title



## Slide 6 Title



## Slide 7 Title



## Slide 8 Title



## Slide 9 Title



## Slide 10 Title






